// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ofx_info
int ofx_info(SEXP path);
RcppExport SEXP _rofx_ofx_info(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ofx_info(path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rofx_ofx_info", (DL_FUNC) &_rofx_ofx_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rofx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
